package com.nimbalyst.app.wiki

import com.google.gson.JsonElement
import com.google.gson.JsonObject
import com.google.gson.JsonParser
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * The Kotlin reader against the shared format fixtures in
 * `packages/local-wiki/fixtures`. `expected.json` in each case is generated by
 * the TypeScript library, and the Swift reader tests against the same files.
 */
class LocalWikiReaderTest {
    private val fixtures = File("../../local-wiki/fixtures")

    private fun cases(): List<String> =
        fixtures.listFiles().orEmpty().filter { File(it, "expected.json").isFile }.map { it.name }.sorted()

    private fun expected(name: String): JsonObject =
        JsonParser.parseString(File(fixtures, "$name/expected.json").readText()).asJsonObject

    private fun read(name: String, expected: JsonObject = expected(name)): WikiSnapshot =
        LocalWikiReader.read(WikiDiskSource(File(fixtures, "$name/wiki")), WikiTypes.parse(expected.getAsJsonArray("types")))

    /** A node as plain values; nulls are dropped, since the generator omits `conflictOf` when absent. */
    private fun shape(node: WikiNode): Map<String, Any?> = when (node) {
        is WikiNode.Page -> mapOf(
            "kind" to "page",
            "id" to node.page.id,
            "title" to node.page.title,
            "path" to node.page.path,
            "dir" to node.page.dir,
            "type" to node.page.type,
            "order" to node.page.order,
            "documentType" to node.page.documentType,
            "fields" to node.page.fields.associate { it.name to it.value },
            "conflictOf" to node.page.conflictOf,
            "children" to node.children.map(::shape),
        )
        is WikiNode.Table -> mapOf(
            "kind" to "table",
            "typeId" to node.table.typeId,
            "title" to node.table.title,
            "path" to node.table.path,
            "header" to node.table.header,
            "rows" to node.table.rows.map { row ->
                mapOf("id" to row.id, "title" to row.title, "fields" to row.fields.associate { it.name to it.value })
            },
        )
    }.filterValues { it != null }

    private fun shape(json: JsonElement): Any? = when {
        json.isJsonNull -> null
        json.isJsonArray -> json.asJsonArray.map(::shape)
        json.isJsonPrimitive && json.asJsonPrimitive.isNumber -> json.asDouble
        json.isJsonPrimitive && json.asJsonPrimitive.isBoolean -> json.asBoolean
        json.isJsonPrimitive -> json.asString
        else -> json.asJsonObject.entrySet().associate { (key, value) ->
            key to if (key == "fields") value.asJsonObject.entrySet().associate { (k, v) -> k to WikiValue.fromJson(v) } else shape(value)
        }.filterValues { it != null }
    }

    @Test
    fun fixturesMatchTheLibrary() {
        val names = cases()
        assertTrue("no fixtures at ${fixtures.absolutePath}", names.isNotEmpty())
        // Written by the desktop round-trip test (projectSyncWikiRoundTrip.test.ts) from what two desktops and a phone synced.
        assertTrue("roundtrip fixture missing", "roundtrip" in names)
        for (name in names) {
            val expected = expected(name)
            val snapshot = read(name, expected)
            assertEquals(name, expected.get("formatVersion").asInt, snapshot.formatVersion)
            assertEquals(name, shape(expected.get("tree")), snapshot.tree.map(::shape))
            assertEquals(name, expected.getAsJsonArray("trashedIds").map { it.asString }, snapshot.trashIds.sorted())
            for (link in expected.getAsJsonArray("links").map { it.asJsonObject }) {
                val from = link.get("from").asString
                val ordinal = link.get("ordinal").asInt
                val targets = snapshot.linkTargets(from)
                assertTrue("$name: $from has no link $ordinal", ordinal < targets.size)
                val target = link.get("target").takeUnless { it.isJsonNull }?.asString
                assertEquals("$name: $from -> ${link.get("path").asString}", target, targets[ordinal])
            }
        }
    }

    /** The same files arriving through sync (paths only, folders implied) read the same. */
    @Test
    fun syncedPathsReadLikeTheFolder() {
        for (name in cases()) {
            val expected = expected(name)
            val root = File(fixtures, "$name/wiki")
            val paths = root.walkTopDown().filter { it.isFile }.map { it.relativeTo(root).invariantSeparatorsPath }
                .filter { !it.startsWith(".trash") }.toList()
            val synced = LocalWikiReader.read(
                WikiPathSource(paths) { File(root, it).readText() },
                WikiTypes.parse(expected.getAsJsonArray("types")),
            )
            assertEquals(name, read(name, expected).tree.map(::shape), synced.tree.map(::shape))
        }
    }

    /** A link tapped in the editor resolves like the scan does: id first, then path. */
    @Test
    fun editorLinkResolution() {
        val snapshot = read("basic")
        val pricing = snapshot.pageAtPath("Competitors/Acme/Pricing.md")!!
        assertEquals("01JBETA0000000000000000000", snapshot.resolveLink(pricing, "../Beta-%20Corp.md", null))
        assertEquals("01JHOME0000000000000000000", snapshot.resolveLink(pricing, "nowhere.md", "id=01JHOME0000000000000000000"))
        assertEquals("01JHOME0000000000000000000", snapshot.resolveLink(pricing, "../../Home.md#partners", null))
        assertNull(snapshot.resolveLink(pricing, "https://example.com", null))
        assertNull(snapshot.resolveLink(pricing, "../../../outside.md", null))
    }

    @Test
    fun frontmatterYamlSubset() {
        val map = WikiYaml.parseMapping(
            """
            a: 1
            b: [x, "y, z", 2.5]
            c:
              - one
              - k: v
                n: 3
            d: { e: true, f: ~ }
            g: '0123'
            h: 2026-10-08
            """.trimIndent()
        )
        assertEquals(WikiValue.Num(1.0), map["a"])
        assertEquals(WikiValue.Arr(listOf(WikiValue.Str("x"), WikiValue.Str("y, z"), WikiValue.Num(2.5))), map["b"])
        assertEquals(
            WikiValue.Arr(listOf(WikiValue.Str("one"), WikiValue.Obj(mapOf("k" to WikiValue.Str("v"), "n" to WikiValue.Num(3.0))))),
            map["c"],
        )
        assertEquals(WikiValue.Obj(mapOf("e" to WikiValue.Bool(true), "f" to WikiValue.Null)), map["d"])
        assertEquals(WikiValue.Str("0123"), map["g"])
        assertEquals(WikiValue.Str("2026-10-08"), map["h"])
        assertThrows(WikiYaml.ParseError::class.java) { WikiYaml.parseMapping("a: 1\na: 2") }
    }
}
