/**
 * The SQLite worker's migration request handlers, lifted out of the worker's
 * dispatch switch.
 *
 * Two reasons this is its own module rather than five more cases in
 * `sqliteWorker.ts`:
 *
 *   - It is where the pipeline's constructor arguments are assembled, and
 *     those had already drifted: the adopt case omitted `configuredProjectCount`
 *     while the orchestrator cases passed it, so every production adoption
 *     assessed itself as having zero projects. `MigrationAdopter`'s own test
 *     passed the field by hand and stayed green throughout. Wiring is only
 *     testable if it is reachable without a live `worker_threads` host, which
 *     is what the injected `MigrationRequestDeps` buys.
 *   - `sqliteWorker.ts` is the largest file in the database layer and every
 *     one of these cases is self-contained.
 *
 * Concurrency guards live here too, so "another migration operation is in
 * progress" has one owner rather than one per case.
 */

import { MigrationOrchestrator, type LivePgliteReader } from '../MigrationOrchestrator';
import { MigrationDryRunner } from '../MigrationDryRunner';
import { MigrationAdopter, type AdopterOptions } from '../MigrationAdopter';
import type { MigrationProgressReporter } from '../MigrationProgressReporter';
import type { PGLiteHandle } from '../PGLiteToSQLiteMigrator';
import {
  MIGRATION_OUTCOME_EVENT,
  type MigrationOperationContext,
  type MigrationOutcome,
} from '../migrationOutcome';

/** Everything the handlers need from the worker host, injected for testability. */
export interface MigrationRequestDeps {
  buildPgliteReader: () => LivePgliteReader;
  closeRunningPglite: () => Promise<void>;
  reopenPgliteAfterClose: (dataDir: string) => Promise<PGLiteHandle>;
  makeReporter: () => MigrationProgressReporter | undefined;
  emit: (event: string, payload: unknown) => void;
  log: (level: 'info' | 'warn' | 'error', msg: string, meta?: unknown) => void;
  countConfiguredProjects: (userDataPath: string) => number;
}

export type MigrationRequestType =
  | 'migrationPreflight'
  | 'migrationStart'
  | 'migrationStartDryRun'
  | 'migrationDryRunStatus'
  | 'migrationAdoptDryRun';

export interface MigrationRequestPayload {
  userDataPath: string;
  schemaDir: string;
  /** Identity for the terminal domain result; generated by the main caller. */
  operationId?: string;
  trigger?: 'auto' | 'manual';
  attempt?: number;
  gaveUp?: boolean;
}

let migrationRunning = false;
let dryRunRunning = false;
let adoptRunning = false;

export async function handleMigrationRequest(
  type: MigrationRequestType,
  payload: MigrationRequestPayload,
  deps: MigrationRequestDeps,
): Promise<unknown> {
  const { userDataPath, schemaDir } = payload;
  const operation = operationContext(payload);
  const onOutcome = (outcome: MigrationOutcome) => deps.emit(MIGRATION_OUTCOME_EVENT, outcome);

  switch (type) {
    case 'migrationPreflight': {
      // No reporter and no close hook: pre-flight only measures.
      const orch = new MigrationOrchestrator({
        userDataPath,
        schemaDir,
        pglite: deps.buildPgliteReader(),
        closeRunningPglite: async () => undefined,
        configuredProjectCount: deps.countConfiguredProjects(userDataPath),
        log: deps.log,
      });
      return orch.preflight();
    }

    case 'migrationStart': {
      if (migrationRunning) throw new Error('Migration already running.');
      if (dryRunRunning) throw new Error('A dry run is in progress; migration is unavailable.');
      migrationRunning = true;
      try {
        const orch = new MigrationOrchestrator({
          userDataPath,
          schemaDir,
          pglite: deps.buildPgliteReader(),
          closeRunningPglite: deps.closeRunningPglite,
          reopenPgliteAfterClose: deps.reopenPgliteAfterClose,
          configuredProjectCount: deps.countConfiguredProjects(userDataPath),
          onCutoverSuccess: async (info) => {
            deps.emit('db:migration:cutoverSuccess', {
              sqliteDir: info.sqliteDir,
              pgliteMigratedDir: info.pgliteMigratedDir,
            });
          },
          onOutcome,
          operation,
          reporter: deps.makeReporter(),
          log: deps.log,
        });
        const summary = await orch.run();
        return { summary };
      } finally {
        migrationRunning = false;
      }
    }

    case 'migrationStartDryRun': {
      if (dryRunRunning) throw new Error('Dry run already in progress.');
      if (migrationRunning) throw new Error('A migration is in progress; dry run is unavailable.');
      dryRunRunning = true;
      try {
        const dryRunner = new MigrationDryRunner({
          userDataPath,
          schemaDir,
          pglite: deps.buildPgliteReader(),
          reporter: deps.makeReporter(),
          // Match the IPC default: keep the dry-run dir + manifest on success so
          // the user can adopt it later.
          keepArtifacts: true,
          log: deps.log,
        });
        const result = await dryRunner.run();
        return { result };
      } finally {
        dryRunRunning = false;
      }
    }

    case 'migrationDryRunStatus': {
      const adopter = buildAdopter({ userDataPath, schemaDir }, deps, {
        closeRunningPglite: async () => undefined,
      });
      const found = adopter.findDryRunDir();
      if (!found) return { available: false };
      return {
        available: true,
        completedAt: found.manifest.completedAt,
        totalRows: found.manifest.perTable.reduce((s, t) => s + t.rows, 0),
      };
    }

    case 'migrationAdoptDryRun': {
      if (adoptRunning) throw new Error('Adopt already running.');
      if (migrationRunning || dryRunRunning) {
        throw new Error('Another migration operation is in progress.');
      }
      adoptRunning = true;
      try {
        const adopter = buildAdopter({ userDataPath, schemaDir }, deps, {
          closeRunningPglite: deps.closeRunningPglite,
          reopenPgliteAfterClose: deps.reopenPgliteAfterClose,
          reporter: deps.makeReporter(),
          onOutcome,
          operation,
          onCutoverSuccess: async (info) => {
            deps.emit('db:migration:cutoverSuccess', {
              sqliteDir: info.sqliteDir,
              pgliteMigratedDir: info.pgliteMigratedDir,
            });
          },
        });
        const result = await adopter.run();
        return { result };
      } finally {
        adoptRunning = false;
      }
    }

    default:
      throw new Error(`Unhandled migration request: ${String(type)}`);
  }
}

/**
 * One place that builds an adopter, so the status probe and the real adoption
 * cannot be handed different facts. The split that let that happen is exactly
 * the bug this module exists to close.
 */
function buildAdopter(
  base: { userDataPath: string; schemaDir: string },
  deps: MigrationRequestDeps,
  extra: Partial<AdopterOptions>,
): MigrationAdopter {
  return new MigrationAdopter({
    userDataPath: base.userDataPath,
    schemaDir: base.schemaDir,
    pglite: deps.buildPgliteReader(),
    closeRunningPglite: deps.closeRunningPglite,
    configuredProjectCount: deps.countConfiguredProjects(base.userDataPath),
    log: deps.log,
    ...extra,
  });
}

function operationContext(
  payload: MigrationRequestPayload,
): MigrationOperationContext | undefined {
  if (!payload.operationId) return undefined;
  return {
    operationId: payload.operationId,
    trigger: payload.trigger ?? 'manual',
    ...(payload.attempt !== undefined ? { attempt: payload.attempt } : {}),
    ...(payload.gaveUp !== undefined ? { gaveUp: payload.gaveUp } : {}),
  };
}
