import XCTest
@testable import NimbalystNative

/// The Swift reader against the shared format fixtures. `expected.json` in each
/// case is generated by the TypeScript library (`fixtures.test.ts` keeps it honest).
final class WikiReaderTests: XCTestCase {
    private static let fixtures = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent() // Tests
        .deletingLastPathComponent() // NimbalystNative
        .deletingLastPathComponent() // ios
        .deletingLastPathComponent() // packages
        .appendingPathComponent("local-wiki/fixtures")

    struct ExpectedRow: Decodable, Equatable {
        var id: String
        var title: String
        var fields: [String: WikiValue]
    }

    struct ExpectedNode: Decodable, Equatable {
        var kind: String
        var id: String?
        var typeId: String?
        var title: String
        var path: String?
        var dir: String?
        var type: String?
        var order: Double?
        var documentType: String?
        var fields: [String: WikiValue]?
        var conflictOf: String?
        var header: [String]?
        var rows: [ExpectedRow]?
        var children: [ExpectedNode]?
    }

    struct ExpectedLink: Decodable {
        var from: String
        var ordinal: Int
        var path: String
        var id: String?
        var target: String?
    }

    struct Expected: Decodable {
        var formatVersion: Int
        var types: [WikiTypeDef]
        var tree: [ExpectedNode]
        var links: [ExpectedLink]
        var trashedIds: [String]
    }

    private func node(_ node: WikiNode) -> ExpectedNode {
        switch node {
        case .page(let page, let children):
            return ExpectedNode(
                kind: "page", id: page.id, title: page.title, path: page.path, dir: page.dir, type: page.type,
                order: page.order, documentType: page.documentType,
                fields: Dictionary(page.fields.map { ($0.name, $0.value) }, uniquingKeysWith: { _, last in last }),
                conflictOf: page.conflictOf, children: children.map(self.node)
            )
        case .table(let table):
            return ExpectedNode(
                kind: "table", typeId: table.typeId, title: table.title, path: table.path, header: table.header,
                rows: table.rows.map { row in
                    ExpectedRow(id: row.id, title: row.title, fields: Dictionary(row.fields.map { ($0.name, $0.value) }, uniquingKeysWith: { _, last in last }))
                }
            )
        }
    }

    private func cases() throws -> [String] {
        try FileManager.default.contentsOfDirectory(atPath: Self.fixtures.path)
            .filter { FileManager.default.fileExists(atPath: Self.fixtures.appendingPathComponent("\($0)/expected.json").path) }
            .sorted()
    }

    private func load(_ name: String) throws -> (Expected, WikiSnapshot) {
        let caseDir = Self.fixtures.appendingPathComponent(name)
        let expected = try JSONDecoder().decode(Expected.self, from: Data(contentsOf: caseDir.appendingPathComponent("expected.json")))
        let snapshot = LocalWikiReader.read(WikiDiskSource(root: caseDir.appendingPathComponent("wiki")), types: expected.types)
        return (expected, snapshot)
    }

    func testFixturesMatchTheLibrary() throws {
        let names = try cases()
        XCTAssertFalse(names.isEmpty, "no fixtures at \(Self.fixtures.path)")
        // Written by the desktop round-trip test (`projectSyncWikiRoundTrip.test.ts`) from what two desktops and a phone synced.
        XCTAssertTrue(names.contains("roundtrip"), "roundtrip fixture missing")
        for name in names {
            let (expected, snapshot) = try load(name)
            XCTAssertEqual(snapshot.formatVersion, expected.formatVersion, name)
            XCTAssertEqual(snapshot.tree.map(node), expected.tree, name)
            XCTAssertEqual(snapshot.trashIds.sorted(), expected.trashedIds, name)
            for link in expected.links {
                let targets = snapshot.linkTargets(of: link.from)
                XCTAssertTrue(link.ordinal < targets.count, "\(name): \(link.from) has no link \(link.ordinal)")
                guard link.ordinal < targets.count else { continue }
                XCTAssertEqual(targets[link.ordinal], link.target, "\(name): \(link.from) -> \(link.path)")
            }
        }
    }

    /// The same files arriving through sync (paths only, folders implied) read the same.
    func testSyncedPathsReadLikeTheFolder() throws {
        for name in try cases() {
            let (expected, disk) = try load(name)
            let root = Self.fixtures.appendingPathComponent("\(name)/wiki")
            let paths = FileManager.default.enumerator(atPath: root.path)!.compactMap { $0 as? String }
                .filter { !$0.hasPrefix(".trash") }
                .filter { path in
                    var isDirectory: ObjCBool = false
                    FileManager.default.fileExists(atPath: root.appendingPathComponent(path).path, isDirectory: &isDirectory)
                    return !isDirectory.boolValue
                }
            let synced = LocalWikiReader.read(WikiPathSource(paths: paths) { try? String(contentsOf: root.appendingPathComponent($0), encoding: .utf8) }, types: expected.types)
            XCTAssertEqual(synced.tree.map(node), disk.tree.map(node), name)
        }
    }

    /// A link tapped in the editor resolves like the scan does: id first, then path.
    func testEditorLinkResolution() throws {
        let (_, snapshot) = try load("basic")
        let pricing = try XCTUnwrap(snapshot.page(atPath: "Competitors/Acme/Pricing.md"))
        XCTAssertEqual(snapshot.resolveLink(from: pricing, destination: "../Beta-%20Corp.md", title: nil), "01JBETA0000000000000000000")
        XCTAssertEqual(snapshot.resolveLink(from: pricing, destination: "nowhere.md", title: "id=01JHOME0000000000000000000"), "01JHOME0000000000000000000")
        XCTAssertEqual(snapshot.resolveLink(from: pricing, destination: "../../Home.md#partners", title: nil), "01JHOME0000000000000000000")
        XCTAssertNil(snapshot.resolveLink(from: pricing, destination: "https://example.com", title: nil))
        XCTAssertNil(snapshot.resolveLink(from: pricing, destination: "../../../outside.md", title: nil))
    }

    func testFrontmatterYAMLSubset() throws {
        let map = try WikiYAML.parseMapping("""
        a: 1
        b: [x, "y, z", 2.5]
        c:
          - one
          - k: v
            n: 3
        d: { e: true, f: ~ }
        g: '0123'
        h: 2026-10-08
        """)
        XCTAssertEqual(map["a"], .number(1))
        XCTAssertEqual(map["b"], .array([.string("x"), .string("y, z"), .number(2.5)]))
        XCTAssertEqual(map["c"], .array([.string("one"), .object(["k": .string("v"), "n": .number(3)])]))
        XCTAssertEqual(map["d"], .object(["e": .bool(true), "f": .null]))
        XCTAssertEqual(map["g"], .string("0123"))
        XCTAssertEqual(map["h"], .string("2026-10-08"))
        XCTAssertThrowsError(try WikiYAML.parseMapping("a: 1\na: 2"))
    }

    private func memoryWiki(_ files: [String: String]) -> WikiSnapshot {
        LocalWikiReader.read(WikiPathSource(paths: Array(files.keys)) { files[$0] }, types: [])
    }

    /// A version the reader cannot compare (non-integral, infinite, missing) is
    /// unsupported, not a crash, and every way of opening its pages is read-only.
    func testFormatVersionGatesEditing() {
        let page = "Home.md"
        for (marker, unsupported) in [
            ("formatVersion: 1", false), ("formatVersion: 2", true), ("formatVersion: .inf", true),
            ("formatVersion: .nan", true), ("formatVersion: 1.5", true), ("formatVersion: 1e300", true), ("tables: {}", true),
        ] {
            let snapshot = memoryWiki([".nimbalyst-wiki.yaml": marker, page: "---\nid: H\n---\nHi\n"])
            XCTAssertEqual(snapshot.isUnsupportedVersion, unsupported, marker)
            let role = WikiDocuments.role(of: "wiki/\(page)", folder: "wiki", snapshot: snapshot)
            if unsupported { XCTAssertEqual(role, .unsupportedFormat, marker) }
            else if case .page = role {} else { XCTFail("\(marker): \(role)") }
        }
        XCTAssertFalse(memoryWiki([page: "Hi"]).isUnsupportedVersion, "a marker that has not synced yet")
    }

    /// Links written in a wiki page stay in the wiki; others resolve beside their file.
    func testWikiLinksStayInsideTheWiki() {
        let snapshot = memoryWiki([
            ".nimbalyst-wiki.yaml": "formatVersion: 1",
            "Home.md": "---\nid: H\n---\n",
            "Docs/Guide.md": "---\nid: G\n---\n",
        ])
        let target = { (href: String, from: String) in
            WikiDocuments.linkTarget(href: href, title: nil, fromRelativePath: from, folder: "kb/wiki", snapshot: snapshot)
        }
        XCTAssertEqual(target("../Home.md", "kb/wiki/Docs/Guide.md"), .document("kb/wiki/Home.md"))
        XCTAssertEqual(target("../../private.md", "kb/wiki/Docs/Guide.md"), .none)
        XCTAssertEqual(target("missing.md", "kb/wiki/Home.md"), .none)
        XCTAssertEqual(target("../private.md", "kb/notes/a.md"), .document("kb/private.md"))
        XCTAssertEqual(target("https://example.com", "kb/wiki/Home.md"), .external(URL(string: "https://example.com")!))
    }

    /// Block scalars match js-yaml, or the file reads as malformed; never an altered value.
    func testBlockScalarsMatchOrAreRejected() throws {
        XCTAssertEqual(try WikiYAML.parseMapping("a: |+\n  x\n")["a"], .string("x\n"))
        XCTAssertEqual(try WikiYAML.parseMapping("a: |+\n  x\n\nb: 1\n")["a"], .string("x\n\n"))
        XCTAssertEqual(try WikiYAML.parseMapping("a: |\n  before\n    code\n  after\n")["a"], .string("before\n  code\nafter\n"))
        // js-yaml: "before\n  code\nafter\n" and "  keep\n"; not reproduced, so refused.
        XCTAssertThrowsError(try WikiYAML.parseMapping("a: >\n  before\n    code\n  after\n"))
        XCTAssertThrowsError(try WikiYAML.parseMapping("summary: |2\n    keep\n"))
        let snapshot = memoryWiki(["P.md": "---\nid: P\nsummary: |2\n    keep\n---\nBody\n"])
        XCTAssertEqual(snapshot.page(atPath: "P.md")?.malformed, true)
    }

    /// A marker that synced but has not been decrypted still locks editing.
    func testUndecryptableMarkerLocksEditing() {
        let snapshot = LocalWikiReader.read(
            WikiPathSource(paths: [".nimbalyst-wiki.yaml", "Home.md"]) { $0 == "Home.md" ? "---\nid: H\n---\n" : nil },
            types: []
        )
        XCTAssertTrue(snapshot.isUnsupportedVersion)
        XCTAssertEqual(WikiDocuments.role(of: "Home.md", folder: "", snapshot: snapshot), .unsupportedFormat)
    }

    /// Values from the TypeScript library (`names.ts`, `links.ts`) for the same inputs.
    func testNamesAndLinkPathsMatchTheLibrary() {
        XCTAssertEqual(WikiFormat.fileStemForTitle("Key\u{00A0}Partners"), "Key Partners")
        XCTAssertEqual(WikiFormat.fileStemForTitle(" \u{00A0}Caf\u{00E9}\u{2003}Notes\u{00A0}"), "Caf\u{00E9} Notes")
        XCTAssertEqual(WikiFormat.nameKey("\u{00C9}COLE"), "\u{00E9}cole")
        let links = WikiFormat.findLinks("[x](%F0%9F%98%80%20Party.md \"id=E1\") [y](100%25.md) [z](bad%E0%A4%A.md) [w](\u{1F600} Party.md)")
        XCTAssertEqual(links.map(\.path), ["\u{1F600} Party.md", "100%.md", "bad%E0%A4%A.md"])
        XCTAssertEqual(links.map(\.id), ["E1", nil, nil])

        // A table whose plural display name holds a no-break space is found by its file.
        let partners = WikiTypeDef(typeId: "partner", displayName: "Partner", displayNamePlural: "Key\u{00A0}Partners", storage: "table", titleField: "title", fields: [])
        let snapshot = LocalWikiReader.read(
            WikiPathSource(paths: ["Key Partners.csv", "\u{1F600} Party.md", "Home.md"]) { path in
                ["Key Partners.csv": "id,title\nR1,Acme\n", "\u{1F600} Party.md": "---\nid: E1\n---\n",
                 "Home.md": "---\nid: H\n---\n[go](%F0%9F%98%80%20Party.md)\n"][path]
            },
            types: [partners]
        )
        XCTAssertEqual(snapshot.tables.map(\.typeId), ["partner"])
        XCTAssertEqual(snapshot.linkTargets(of: "H"), ["E1"])
    }
}
