#!/usr/bin/env bash
#
# Install a macOS handler bundle that routes nimbalyst:// deep links to THIS checkout's
# dev instance.
#
# Why this exists: in dev, Nimbalyst runs inside `node_modules/electron/dist/Electron.app`,
# whose bundle id is the generic `com.github.Electron`. Every checkout, worktree, and npx
# cache on the machine has a copy claiming that same id, so asking macOS to make "Electron"
# the nimbalyst:// handler makes the OS launch an arbitrary one of them with no app path --
# the blank Electron welcome window -- and the deep link never reaches Nimbalyst. The main
# process therefore no longer claims the scheme in dev (see utils/protocolRegistration.ts);
# this tiny AppleScript applet, with its own bundle id, claims it instead and forwards the
# URL to the dev app, which routes it through the existing single-instance handler.
#
# Usage:
#   scripts/install-dev-url-handler.sh              install and make it the default handler
#   scripts/install-dev-url-handler.sh --clean-stray  also drop stray dev Electron.app registrations
#   scripts/install-dev-url-handler.sh --uninstall  remove the handler bundle
#
# Packaged builds are unaffected -- they claim the scheme with com.nimbalyst.electron.

set -euo pipefail

if [[ "$(uname)" != "Darwin" ]]; then
  echo "This script is macOS-only; Windows and Linux register the scheme from the app itself." >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL_DIR="$HOME/Library/Application Support/@nimbalyst/dev-url-handler"
APP_PATH="$INSTALL_DIR/Nimbalyst Dev URL Handler.app"
BUNDLE_ID="com.nimbalyst.dev-url-handler"
LSREGISTER="/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister"

uninstall() {
  if [[ -d "$APP_PATH" ]]; then
    "$LSREGISTER" -u "$APP_PATH" >/dev/null 2>&1 || true
    rm -rf "$APP_PATH"
    echo "Removed $APP_PATH"
  else
    echo "Nothing to remove at $APP_PATH"
  fi
}

# Dev Electron.app copies register themselves with LaunchServices just by being launched.
# They all share com.github.Electron, so leaving a pile of them registered is what lets the
# OS pick a random one. Drop the ones that are not this checkout's.
clean_stray_registrations() {
  local dump count=0
  dump="$(mktemp)"
  "$LSREGISTER" -dump 2>/dev/null > "$dump"
  while IFS= read -r bundle; do
    [[ -z "$bundle" ]] && continue
    [[ "$bundle" == "$REPO_ROOT/node_modules/electron/dist/Electron.app" ]] && continue
    [[ -d "$bundle" ]] || continue
    "$LSREGISTER" -u "$bundle" >/dev/null 2>&1 || true
    echo "  unregistered $bundle"
    count=$((count + 1))
  done < <(grep -oE '/[^ ]*/node_modules/[^ ]*electron/dist/Electron\.app' "$dump" | sort -u)
  rm -f "$dump"
  echo "Unregistered $count stray dev Electron.app bundle(s)."
}

if [[ "${1:-}" == "--uninstall" ]]; then
  uninstall
  exit 0
fi

ELECTRON_BIN="$REPO_ROOT/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron"
APP_DIR="$REPO_ROOT/packages/electron"

if [[ ! -x "$ELECTRON_BIN" ]]; then
  echo "Electron binary not found at $ELECTRON_BIN -- run npm install first." >&2
  exit 1
fi

mkdir -p "$INSTALL_DIR"
rm -rf "$APP_PATH"

SCRIPT_SRC="$(mktemp -t nimbalyst-dev-url-handler).applescript"
cat > "$SCRIPT_SRC" <<EOF
-- Generated by scripts/install-dev-url-handler.sh for $REPO_ROOT -- do not edit by hand.
on open location this_URL
	do shell script quoted form of "$ELECTRON_BIN" & " " & quoted form of "$APP_DIR" & " " & quoted form of this_URL & " > /dev/null 2>&1 &"
end open location

on run
	display notification "Deep links route to $REPO_ROOT" with title "Nimbalyst dev URL handler"
end run
EOF

osacompile -o "$APP_PATH" "$SCRIPT_SRC"
rm -f "$SCRIPT_SRC"

PLIST="$APP_PATH/Contents/Info.plist"
plutil -replace CFBundleIdentifier -string "$BUNDLE_ID" "$PLIST"
plutil -replace CFBundleName -string "Nimbalyst Dev URL Handler" "$PLIST"
plutil -replace LSUIElement -bool true "$PLIST" 2>/dev/null || plutil -insert LSUIElement -bool true "$PLIST"
plutil -replace CFBundleURLTypes -json '[{"CFBundleURLName":"Nimbalyst Dev","CFBundleURLSchemes":["nimbalyst"]}]' "$PLIST" 2>/dev/null \
  || plutil -insert CFBundleURLTypes -json '[{"CFBundleURLName":"Nimbalyst Dev","CFBundleURLSchemes":["nimbalyst"]}]' "$PLIST"

# The bundle was edited after osacompile signed it, so re-seal it ad-hoc.
codesign --force --deep --sign - "$APP_PATH" >/dev/null 2>&1

if [[ "${1:-}" == "--clean-stray" ]]; then
  clean_stray_registrations
fi

"$LSREGISTER" -f "$APP_PATH"

# NSWorkspace is the only supported way to set a default URL-scheme handler.
swift -e '
import AppKit
let appPath = CommandLine.arguments[1]
NSWorkspace.shared.setDefaultApplication(at: URL(fileURLWithPath: appPath), toOpenURLsWithScheme: "nimbalyst") { error in
    if let error { FileHandle.standardError.write("Failed to set default handler: \(error)\n".data(using: .utf8)!); exit(1) }
    exit(0)
}
RunLoop.main.run()
' "$APP_PATH"

echo "Installed $APP_PATH"
echo "nimbalyst:// deep links now open $REPO_ROOT"
echo "Note: the dev app must be built (packages/electron/out) for a forwarded link to land."
