import { createStore } from 'jotai';
import { beforeEach, expect, it, vi } from 'vitest';
import { initProjectAppearanceListener } from '../../listeners/projectAppearanceListeners';
import { projectAppearanceAtom, saveProjectAppearanceAtom } from '../projectAppearance';
const a = '/projects/FileRocket';
const b = '/projects/FileRocket_fix';
beforeEach(() => { (window as any).electronAPI = { invoke: vi.fn(), on: vi.fn() }; for (const key of projectAppearanceAtom.getParams()) projectAppearanceAtom.remove(key); });
it('shares one load across consumers and does not let an old read overwrite a broadcast', async () => {
  const store = createStore();
  let resolve!: (value: unknown) => void;
  const invoke = vi.fn(() => new Promise(r => { resolve = r; }));
  let broadcast!: (value: unknown) => void;
  const unsubscribe = vi.fn();
  window.electronAPI.invoke = invoke;
  window.electronAPI.on = vi.fn((_channel, callback) => { broadcast = callback; return unsubscribe; });
  const stop = initProjectAppearanceListener(store);
  const stopA = store.sub(projectAppearanceAtom(a), () => {});
  const stopAgain = store.sub(projectAppearanceAtom(a), () => {});
  expect(invoke).toHaveBeenCalledTimes(1);
  broadcast({ workspacePath: a, revision: 2, appearance: { initials: 'FR' } });
  resolve({ revision: 1, appearance: {} });
  await Promise.resolve();
  expect(store.get(projectAppearanceAtom(a)).snapshot?.appearance.initials).toBe('FR');
  broadcast({ workspacePath: '/not-observed', revision: 3, appearance: {} });
  expect(Array.from(projectAppearanceAtom.getParams())).not.toContain('/not-observed');
  stopA(); stopAgain(); stop();
  expect(unsubscribe).toHaveBeenCalledTimes(1);
});
it('saves only changed fields for the specified workspace and propagates failures', async () => {
  const store = createStore();
  store.set(projectAppearanceAtom(b), { snapshot: { revision: 0, appearance: { initials: 'FX' } } });
  const invoke = vi.fn().mockResolvedValue({ revision: 1, appearance: { initials: 'FR' } });
  window.electronAPI.invoke = invoke;
  await store.set(saveProjectAppearanceAtom, a, { initials: 'FR' });
  expect(invoke).toHaveBeenCalledWith('project-appearance:update', a, { initials: 'FR' });
  expect(store.get(projectAppearanceAtom(b)).snapshot?.appearance.initials).toBe('FX');
  invoke.mockRejectedValueOnce(new Error('Disk full'));
  await expect(store.set(saveProjectAppearanceAtom, a, { color: '#123456' })).rejects.toThrow('Disk full');
  expect(store.get(projectAppearanceAtom(a)).snapshot?.appearance).toEqual({ initials: 'FR' });
});
