#!/usr/bin/env node
// GENERATED by scripts/build-wiki-plugin.mjs from packages/extensions/knowledge/src/sessionInputs. Do not edit; edit the source and re-run the script.

// packages/extensions/knowledge/src/sessionInputs/server.ts
import { execFileSync } from "node:child_process";
import { readFileSync as readFileSync2 } from "node:fs";
import { createInterface } from "node:readline";
import { fileURLToPath } from "node:url";
import path2 from "node:path";

// packages/collab-protocol/src/consoleLinks.ts
var CONSOLE_LINK_ORIGIN = "https://console.nimbalyst.com";
var LOCAL_SEGMENT = "app";
var CITATION_KINDS = ["prompt", "answer", "comment"];
var AGENT_CITATION_KINDS = ["prompt", "answer"];
var CITATION_AGENTS = ["claude-code"];
function enc(value) {
  return encodeURIComponent(value).replace(/[()'*!~]/g, (ch) => `%${ch.charCodeAt(0).toString(16).toUpperCase()}`);
}
function dec(value) {
  try {
    const decoded = decodeURIComponent(value);
    return decoded === "" ? null : decoded;
  } catch {
    return null;
  }
}
function scopePrefix(scope) {
  return scope === "local" ? `/${LOCAL_SEGMENT}` : `/org/${enc(scope.orgId)}/project/${enc(scope.projectId)}`;
}
function viewTail(view) {
  if (view.kind === "type") return `/view/type/${enc(view.typeId)}`;
  return view.marks === "all" ? "/view/marks" : `/view/marks?kind=${view.marks}`;
}
function consoleLinkPath(target) {
  if (target.kind === "citation") {
    const segments = [...target.agent ? [target.agent] : [], target.sessionId, target.inputKind, target.key];
    return `/${LOCAL_SEGMENT}/cite/${segments.map(enc).join("/")}`;
  }
  if (target.kind === "commentCitation") {
    return `${scopePrefix(target.scope)}/document/${enc(target.pageId)}?comment=${enc(target.commentId)}`;
  }
  const prefix = scopePrefix(target.scope);
  const local = target.scope === "local";
  switch (target.kind) {
    case "page":
      return `${prefix}/${local ? "page" : "document"}/${enc(target.pageId)}`;
    case "item":
      return `${prefix}/${local ? "item" : "page/item"}/${enc(target.itemRef)}`;
    case "type":
      return `${prefix}/${local ? "type" : "page/type"}/${enc(target.typeId)}`;
    case "view":
      return `${prefix}${viewTail(target.view)}`;
  }
}
function buildConsoleLink(target, origin = CONSOLE_LINK_ORIGIN) {
  return `${origin}${consoleLinkPath(target)}`;
}
function parsePath(pathname, search) {
  const raw = pathname.split("/").slice(1);
  if (raw.some((segment) => segment === "")) return null;
  let scope;
  let rest;
  if (raw[0] === LOCAL_SEGMENT) {
    scope = "local";
    rest = raw.slice(1);
  } else if (raw[0] === "org" && raw[2] === "project" && raw.length > 4) {
    const orgId = dec(raw[1]);
    const projectId = dec(raw[3]);
    if (!orgId || !projectId) return null;
    scope = { orgId, projectId };
    rest = raw.slice(4);
  } else {
    return null;
  }
  const local = scope === "local";
  const [head, a, b, c] = rest;
  if (rest[0] === "view") {
    if (rest.length === 3 && a === "type") {
      const typeId = dec(b);
      return typeId ? { kind: "view", scope, view: { kind: "type", typeId } } : null;
    }
    if (rest.length === 2 && a === "marks") {
      const kind = search.get("kind");
      if (kind === null) return { kind: "view", scope, view: { kind: "marks", marks: "all" } };
      return kind === "decided" || kind === "open" ? { kind: "view", scope, view: { kind: "marks", marks: kind } } : null;
    }
    return null;
  }
  if (local) {
    if (head === "cite" && rest.length === 4) {
      const sessionId = dec(a);
      const key = dec(c);
      const inputKind = b;
      if (!sessionId || !key || !CITATION_KINDS.includes(inputKind)) return null;
      return { kind: "citation", sessionId, inputKind, key };
    }
    if (head === "cite" && rest.length === 5) {
      const agent = a;
      const sessionId = dec(b);
      const inputKind = c;
      const key = dec(rest[4]);
      if (!CITATION_AGENTS.includes(agent) || !sessionId || !key || !AGENT_CITATION_KINDS.includes(inputKind)) return null;
      return { kind: "citation", agent, sessionId, inputKind, key };
    }
    if (rest.length !== 2) return null;
    const id = dec(a);
    if (!id) return null;
    if (head === "page") return { kind: "page", scope, pageId: id };
    if (head === "item") return { kind: "item", scope, itemRef: id };
    if (head === "type") return { kind: "type", scope, typeId: id };
    return null;
  }
  if (head === "document" && rest.length === 2) {
    const pageId = dec(a);
    if (!pageId) return null;
    const comment = search.get("comment");
    if (comment === null) return { kind: "page", scope, pageId };
    return comment && scope !== "local" ? { kind: "commentCitation", scope, pageId, commentId: comment } : null;
  }
  if ((head === "page" || head === "trackers") && rest.length === 3) {
    const id = dec(b);
    if (!id) return null;
    if (a === "item") return { kind: "item", scope, itemRef: id };
    if (a === "type") return { kind: "type", scope, typeId: id };
  }
  return null;
}
function parseConsoleLink(href, options = {}) {
  if (!href) return null;
  let url;
  try {
    url = new URL(href);
  } catch {
    return null;
  }
  const origins = [CONSOLE_LINK_ORIGIN, ...options.origins ?? []];
  if (!origins.includes(url.origin)) return null;
  return parsePath(url.pathname, url.searchParams);
}

// packages/runtime/src/core/citationSyntax.ts
var LEGACY_HUMAN_CITATION_BASE = "nimbalyst://cite/";
var SOURCE_CITATION_TITLE = "cite";
var TITLE_FIELDS = [
  ["by", "by"],
  ["email", "email"],
  ["at", "at"],
  ["context", "ctx"],
  ["sessionTitle", "in"],
  ["quote", "quote"]
];
var QUOTED_ENCODE = /[%'"\\\r\n[\]()`*_~|<>]/g;
var BARE_VALUE = /^[\w.:+@,/-]+$/;
var TARGET_ENCODE = /[\s()"<>]/g;
var TARGET_DECODE = /%(20|28|29|22|3C|3E|09|0A|0D)/gi;
function isCitationInputKind(value) {
  return value === "prompt" || value === "answer" || value === "comment";
}
function percent(ch) {
  return `%${ch.charCodeAt(0).toString(16).toUpperCase().padStart(2, "0")}`;
}
function encodeQuoted(value) {
  return value.replace(QUOTED_ENCODE, percent);
}
function decodeValue(value) {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
}
function formatTitleValue(value) {
  return BARE_VALUE.test(value) ? value : `'${encodeQuoted(value)}'`;
}
function cleanLabel(label) {
  return label.replace(/[[\]\r\n]/g, " ").replace(/\s+/g, " ").trim();
}
function citationInitials(name) {
  const words = (name ?? "").trim().split(/\s+/).filter(Boolean);
  if (words.length === 0) return "?";
  const letters = words.length === 1 ? words[0].slice(0, 1) : words[0].slice(0, 1) + words[words.length - 1].slice(0, 1);
  return letters.toUpperCase();
}
function buildHumanCitationHref(ref) {
  return buildConsoleLink({
    kind: "citation",
    ...ref.agent ? { agent: ref.agent } : {},
    sessionId: ref.sessionId,
    inputKind: ref.inputKind,
    key: ref.key
  });
}
function parseHumanCitationHref(href) {
  const target = parseConsoleLink(href);
  if (target?.kind === "citation") {
    return { ...target.agent ? { agent: target.agent } : {}, sessionId: target.sessionId, inputKind: target.inputKind, key: target.key };
  }
  if (!href.startsWith(LEGACY_HUMAN_CITATION_BASE)) return null;
  const segments = href.slice(LEGACY_HUMAN_CITATION_BASE.length).split("/");
  if (segments.length !== 3) return null;
  const [sessionId, inputKind, key] = segments.map(decodeValue);
  if (!sessionId || !key || !isCitationInputKind(inputKind)) return null;
  return { sessionId, inputKind, key };
}
function encodeTarget(target) {
  return target.replace(TARGET_ENCODE, percent);
}
function decodeTarget(destination) {
  return destination.replace(TARGET_DECODE, (_match, hex) => String.fromCharCode(parseInt(hex, 16)));
}
function isSourceTitle(title) {
  return title?.trim().split(/\s+/)[0] === SOURCE_CITATION_TITLE;
}
function buildCitationHref(citation) {
  return citation.kind === "source" ? encodeTarget(citation.target) : buildHumanCitationHref(citation);
}
function formatCitationTitle(citation) {
  if (citation.kind === "source") return SOURCE_CITATION_TITLE;
  const tokens = [];
  for (const [field, name] of TITLE_FIELDS) {
    const value = citation[field];
    if (typeof value === "string" && value !== "") tokens.push(`${name}=${formatTitleValue(value)}`);
  }
  return tokens.length > 0 ? tokens.join(" ") : null;
}
function parseCitationTitle(title) {
  const out = {};
  const tokenPattern = /([A-Za-z][\w-]*)=(?:'([^']*)'|(\S+))/g;
  let match;
  while ((match = tokenPattern.exec(title)) !== null) {
    const field = TITLE_FIELDS.find(([, name]) => name === match[1])?.[0];
    if (!field) continue;
    out[field] = decodeValue(match[2] ?? match[3] ?? "");
  }
  return out;
}
function parseCitationLink(label, href, title) {
  const ref = parseHumanCitationHref(href);
  if (ref) return { kind: "human", ...ref, label, ...title ? parseCitationTitle(title) : {} };
  if (isSourceTitle(title)) {
    const target = decodeTarget(href);
    return target ? { kind: "source", target, label } : null;
  }
  return null;
}
function citationsEqual(a, b) {
  if (a.kind !== b.kind || a.label !== b.label) return false;
  if (a.kind === "source" || b.kind === "source") {
    return a.kind === "source" && b.kind === "source" && a.target === b.target;
  }
  return sameHumanTarget(a, b) && TITLE_FIELDS.every(([field]) => (a[field] ?? "") === (b[field] ?? ""));
}
function sameHumanTarget(a, b) {
  return a.agent === b.agent && a.sessionId === b.sessionId && a.inputKind === b.inputKind && a.key === b.key;
}
function sameTarget(a, b) {
  if (a.kind === "source" || b.kind === "source") {
    return a.kind === "source" && b.kind === "source" && a.target === b.target;
  }
  return sameHumanTarget(a, b);
}
function formatCitationMarkdown(citation, rawTitle, rawHref) {
  const label = cleanLabel(citation.label) || (citation.kind === "human" ? citationInitials(citation.by) : "source");
  const normalized = { ...citation, label };
  let href = buildCitationHref(normalized);
  if (rawHref && rawHref !== href) {
    const reread = parseCitationLink(label, rawHref, formatCitationTitle(normalized));
    if (reread && sameTarget(reread, normalized)) href = rawHref;
  }
  let title = formatCitationTitle(normalized);
  if (rawTitle != null) {
    const reparsed = parseCitationLink(label, href, rawTitle);
    if (reparsed && citationsEqual(reparsed, normalized)) title = rawTitle;
  }
  return `[${label}](${href}${title ? ` "${title}"` : ""})`;
}
function createHumanCitation(input) {
  return { ...input, kind: "human", label: input.label ?? citationInitials(input.by) };
}

// packages/extensions/knowledge/src/sessionInputs/claudeTranscriptInputs.ts
var MAX_QUOTE_LENGTH = 400;
function asRecord(value) {
  return value && typeof value === "object" && !Array.isArray(value) ? value : null;
}
function shortenQuote(text, max = MAX_QUOTE_LENGTH) {
  const clean = text.trim().replace(/\s+\n/g, "\n");
  if (clean.length <= max) return clean;
  const cut = clean.slice(0, max);
  const lastSpace = cut.lastIndexOf(" ");
  return `${(lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut).trimEnd()}\u2026`;
}
var PASTED = /<pasted_content\b[^>]*>[\s\S]*?<\/pasted_content>/g;
var COMMAND_NAME = /<command-name>\s*(\/[^<\s]+)\s*<\/command-name>/;
var COMMAND_ARGS = /<command-args>([\s\S]*?)<\/command-args>/;
function messageText(content) {
  if (typeof content === "string") return content;
  if (!Array.isArray(content)) return null;
  const texts = [];
  for (const block of content) {
    const record = asRecord(block);
    if (record?.type === "text" && typeof record.text === "string") texts.push(record.text);
    else if (record?.type !== "image") return null;
  }
  return texts.join("\n");
}
function isTypedByPerson(record) {
  if (record.isMeta || record.isCompactSummary || record.toolUseResult !== void 0) return false;
  if (record.entrypoint === "sdk-cli") return false;
  if (record.turnOrigin !== void 0 && record.turnOrigin !== "human") return false;
  if (record.promptSource !== void 0) return record.promptSource === "typed";
  return true;
}
function promptEntry(record) {
  const raw = messageText(record.message?.content);
  if (raw === null) return null;
  const command = COMMAND_NAME.exec(raw);
  if (command) {
    const args = (COMMAND_ARGS.exec(raw)?.[1] ?? "").trim();
    return args ? { context: command[1], quote: shortenQuote(args.replace(PASTED, "[pasted]")) } : null;
  }
  if (record.promptSource === void 0 && raw.trimStart().startsWith("<")) return null;
  if (/^\s*<(local-command-|task-notification|system-reminder)/.test(raw)) return null;
  const text = raw.replace(PASTED, "[pasted]").trim();
  if (!text || text === "[pasted]") return null;
  return { context: "Prompt", quote: shortenQuote(text) };
}
function optionLabels(question) {
  const options = Array.isArray(question?.options) ? question.options : [];
  return options.map((option) => typeof option === "string" ? option : asRecord(option)?.label).filter((label) => typeof label === "string");
}
function answerEntries(callId, askedQuestions, result) {
  const answers = asRecord(result.answers);
  if (!answers) return [];
  const questions = Array.isArray(result.questions) ? result.questions : askedQuestions;
  const annotations = asRecord(result.annotations) ?? {};
  const answered = Object.keys(answers).filter((question) => typeof answers[question] === "string" && answers[question].trim());
  return answered.map((questionText, index) => {
    const position = questions.findIndex((question) => question?.question === questionText);
    const labels = optionLabels(questions[position]);
    const answer = String(answers[questionText]).trim();
    const otherParts = labels.length === 0 || labels.includes(answer) ? [] : answer.split(", ").filter((part) => !labels.includes(part));
    const note = typeof asRecord(annotations[questionText])?.notes === "string" ? asRecord(annotations[questionText]).notes.trim() : "";
    const typedText = [otherParts.join(", "), note].filter(Boolean).join(" / ");
    const typed = typedText.length > 0;
    return {
      key: answered.length > 1 ? `${callId}~${position >= 0 ? position : index}` : callId,
      context: questionText,
      quote: shortenQuote(typed ? typedText : answer),
      ...typed && typedText !== answer ? { answer } : {},
      typed
    };
  });
}
function toolResultBlock(record) {
  const content = record.message?.content;
  const first = Array.isArray(content) ? asRecord(content[0]) : null;
  return first?.type === "tool_result" ? first : null;
}
function citableInputsFromTranscript(jsonl, author) {
  const askCalls = /* @__PURE__ */ new Map();
  const answeredCalls = /* @__PURE__ */ new Set();
  const inputs = [];
  const push = (kind, at, entry) => {
    inputs.push({
      kind,
      key: entry.key,
      sessionId: author.sessionId,
      agent: "claude-code",
      by: author.by,
      ...author.email ? { email: author.email } : {},
      at,
      context: entry.context,
      quote: entry.quote,
      ...entry.answer !== void 0 ? { answer: entry.answer } : {},
      ...entry.typed !== void 0 ? { typed: entry.typed } : {},
      citation: formatCitationMarkdown(createHumanCitation({
        agent: "claude-code",
        sessionId: author.sessionId,
        inputKind: kind,
        key: entry.key,
        by: author.by,
        ...author.email ? { email: author.email } : {},
        at,
        ...kind === "answer" ? { context: `answering ${shortenQuote(entry.context, 80)}` } : entry.context !== "Prompt" ? { context: entry.context } : {},
        quote: entry.quote
      }))
    });
  };
  for (const line of jsonl.split("\n")) {
    if (!line.trim()) continue;
    let record;
    try {
      record = asRecord(JSON.parse(line));
    } catch {
      continue;
    }
    if (!record || record.isSidechain === true) continue;
    const at = typeof record.timestamp === "string" ? record.timestamp : "";
    if (record.type === "assistant") {
      for (const block of Array.isArray(record.message?.content) ? record.message.content : []) {
        if (block?.type === "tool_use" && block.name === "AskUserQuestion" && typeof block.id === "string") {
          askCalls.set(block.id, Array.isArray(block.input?.questions) ? block.input.questions : []);
        }
      }
      continue;
    }
    if (record.type !== "user" || !at) continue;
    const result = toolResultBlock(record);
    if (result) {
      const callId = typeof result.tool_use_id === "string" ? result.tool_use_id : "";
      const asked = askCalls.get(callId);
      const payload = asRecord(record.toolUseResult);
      if (!asked || answeredCalls.has(callId) || result.is_error === true || !payload) continue;
      const entries = answerEntries(callId, asked, payload);
      if (entries.length === 0) continue;
      answeredCalls.add(callId);
      for (const entry of entries) push("answer", at, entry);
      continue;
    }
    if (!isTypedByPerson(record) || typeof record.uuid !== "string") continue;
    const prompt = promptEntry(record);
    if (prompt) push("prompt", at, { key: record.uuid, ...prompt });
  }
  return inputs;
}
function selectInputs(inputs, selection = {}) {
  const kinds = selection.kinds && selection.kinds.length > 0 ? new Set(selection.kinds) : null;
  const query = selection.query?.trim().toLowerCase();
  const limit = Math.min(Math.max(1, Math.floor(selection.limit ?? 50)), 200);
  const matched = inputs.filter((input) => (!kinds || kinds.has(input.kind)) && (!query || `${input.quote}
${input.context}
${input.answer ?? ""}`.toLowerCase().includes(query)));
  return matched.slice(-limit);
}

// packages/extensions/knowledge/src/sessionInputs/claudeTranscriptLocator.ts
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { homedir } from "node:os";
import path from "node:path";
var SAFE_ID = /^[A-Za-z0-9_-]{1,128}$/;
var RECENT_MS = 10 * 60 * 1e3;
function encodeProjectDir(dir) {
  return dir.replace(/[^A-Za-z0-9]/g, "-");
}
function projectsRoot(env) {
  return path.join(env.CLAUDE_CONFIG_DIR || path.join(env.HOME || homedir(), ".claude"), "projects");
}
function listDir(dir) {
  try {
    return readdirSync(dir);
  } catch {
    return [];
  }
}
function jsonlIn(dir) {
  return listDir(dir).filter((name) => name.endsWith(".jsonl")).map((name) => path.join(dir, name));
}
function holdsToolUse(file, toolUseId) {
  let text;
  try {
    text = readFileSync(file, "utf8");
  } catch {
    return false;
  }
  const needle = `"${toolUseId}"`;
  if (!text.includes(needle)) return false;
  for (const line of text.split("\n")) {
    if (!line.includes(needle)) continue;
    try {
      const record = JSON.parse(line);
      const content = record?.type === "assistant" ? record.message?.content : null;
      if (Array.isArray(content) && content.some((block) => block?.type === "tool_use" && block.id === toolUseId)) return true;
    } catch {
    }
  }
  return false;
}
function sessionCandidates(dir, sessionId) {
  const main2 = path.join(dir, `${sessionId}.jsonl`);
  return [
    { file: main2, main: main2 },
    ...jsonlIn(path.join(dir, sessionId, "subagents")).map((file) => ({ file, main: main2 }))
  ];
}
function candidates(env, now) {
  const root = projectsRoot(env);
  const projectDir = env.CLAUDE_PROJECT_DIR ? path.join(root, encodeProjectDir(env.CLAUDE_PROJECT_DIR)) : null;
  const sessionId = env.CLAUDE_CODE_SESSION_ID;
  const out = [];
  if (sessionId && SAFE_ID.test(sessionId)) {
    if (projectDir) out.push(...sessionCandidates(projectDir, sessionId));
    for (const name of listDir(root)) {
      const dir = path.join(root, name);
      if (dir !== projectDir && existsSync(path.join(dir, `${sessionId}.jsonl`))) out.push(...sessionCandidates(dir, sessionId));
    }
  }
  if (projectDir) {
    const recent = (file) => {
      try {
        return now - statSync(file).mtimeMs < RECENT_MS;
      } catch {
        return false;
      }
    };
    for (const file of jsonlIn(projectDir).filter(recent)) out.push({ file, main: file });
    for (const name of listDir(projectDir)) {
      const main2 = path.join(projectDir, `${name}.jsonl`);
      if (!SAFE_ID.test(name)) continue;
      for (const file of jsonlIn(path.join(projectDir, name, "subagents")).filter(recent)) out.push({ file, main: main2 });
    }
  }
  return out;
}
async function locateTranscript(toolUseId, deps) {
  if (!toolUseId || !SAFE_ID.test(toolUseId)) {
    return { ok: false, reason: "This Claude Code did not say which tool call is asking, so the session cannot be confirmed." };
  }
  const now = deps.now ?? Date.now;
  const sleep = deps.sleep ?? ((ms) => new Promise((resolve) => setTimeout(resolve, ms)));
  const deadline = now() + (deps.timeoutMs ?? 3e3);
  for (; ; ) {
    for (const candidate of candidates(deps.env, now())) {
      if (!holdsToolUse(candidate.file, toolUseId)) continue;
      const sessionId = path.basename(candidate.main, ".jsonl");
      if (!SAFE_ID.test(sessionId) || !existsSync(candidate.main)) break;
      return { ok: true, sessionId, path: candidate.main };
    }
    if (now() >= deadline) return { ok: false, reason: "Could not confirm this session's transcript." };
    await sleep(deps.pollMs ?? 20);
  }
}

// packages/extensions/knowledge/src/sessionInputs/server.ts
var TOOL_NAME = "list_session_inputs";
var SERVER_INFO = { name: "nimbalyst-session", version: "0.2.0" };
var DEFAULT_PROTOCOL = "2025-06-18";
var TOOL_DEFINITION = {
  name: TOOL_NAME,
  description: "List what the person at this terminal typed in this Claude Code session that a page may cite: their prompts and their answers to your questions. Each entry has a stable key, who, when, the quote and `citation`: ready markdown to paste right after the sentence it supports. Reads only this session's transcript on this machine; lists nothing when it cannot confirm which transcript is this session's. Pass the signed-in person's name and email from pages_status. Teammates' comments on pages come from list_citable_inputs instead.",
  inputSchema: {
    type: "object",
    properties: {
      kinds: { type: "array", items: { type: "string", enum: ["prompt", "answer"] }, description: "Which inputs to list (default both)." },
      query: { type: "string", description: "Case-insensitive text to match in the quote or context." },
      limit: { type: "number", description: "Maximum entries, newest kept (default 50, max 200)." },
      by: { type: "string", description: "The person's display name, from pages_status `user`." },
      email: { type: "string", description: "The person's email, from pages_status `user`." }
    }
  },
  annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false }
};
function gitConfig(cwd, key) {
  try {
    return execFileSync("git", ["config", "--get", key], { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"], timeout: 2e3 }).trim() || void 0;
  } catch {
    return void 0;
  }
}
function textResult(value, isError = false) {
  return { content: [{ type: "text", text: JSON.stringify(value) }], ...isError ? { isError: true } : {} };
}
var asString = (value) => typeof value === "string" && value.trim() ? value.trim() : void 0;
async function callListSessionInputs(params, deps) {
  const args = params?.arguments ?? {};
  const toolUseId = asString(params?._meta?.["claudecode/toolUseId"]);
  const located = await locateTranscript(toolUseId, deps);
  if (!located.ok) {
    return textResult({ inputs: [], notes: [located.reason, "Nothing listed. Mark a decision with the signed-in person from pages_status instead of a quote."] });
  }
  const git = deps.gitIdentity?.() ?? {};
  const by = asString(args.by) ?? git.name;
  const email = asString(args.email) ?? git.email;
  if (!by) return textResult({ inputs: [], notes: ["Pass `by` (and `email`) from pages_status `user`: the citations name the person."] });
  const kinds = Array.isArray(args.kinds) ? args.kinds.filter((kind) => kind === "prompt" || kind === "answer") : void 0;
  const all = citableInputsFromTranscript(readFileSync2(located.path, "utf8"), { sessionId: located.sessionId, by, ...email ? { email } : {} });
  const inputs = selectInputs(all, { kinds, query: asString(args.query), limit: typeof args.limit === "number" ? args.limit : void 0 });
  const notes = inputs.length === 0 ? ["Nothing typed in this session matches."] : [];
  return textResult({ inputs, notes });
}
async function handleMessage(message, deps) {
  const id = message.id ?? null;
  const reply = (result) => ({ jsonrpc: "2.0", id, result });
  if (message.id === void 0) return null;
  switch (message.method) {
    case "initialize":
      return reply({
        protocolVersion: typeof message.params?.protocolVersion === "string" ? message.params.protocolVersion : DEFAULT_PROTOCOL,
        capabilities: { tools: {} },
        serverInfo: SERVER_INFO
      });
    case "ping":
      return reply({});
    case "tools/list":
      return reply({ tools: [TOOL_DEFINITION] });
    case "tools/call":
      if (message.params?.name !== TOOL_NAME) {
        return { jsonrpc: "2.0", id, error: { code: -32602, message: `Unknown tool: ${String(message.params?.name)}` } };
      }
      try {
        return reply(await callListSessionInputs(message.params, deps));
      } catch (err) {
        return reply(textResult({ inputs: [], notes: [`Could not read this session: ${err instanceof Error ? err.message : String(err)}`] }, true));
      }
    default:
      return { jsonrpc: "2.0", id, error: { code: -32601, message: `Method not found: ${String(message.method)}` } };
  }
}
function main() {
  const env = process.env;
  const deps = {
    env: {
      CLAUDE_CODE_SESSION_ID: env.CLAUDE_CODE_SESSION_ID,
      CLAUDE_PROJECT_DIR: env.CLAUDE_PROJECT_DIR,
      CLAUDE_CONFIG_DIR: env.CLAUDE_CONFIG_DIR,
      HOME: env.HOME
    },
    gitIdentity: () => ({ name: gitConfig(env.CLAUDE_PROJECT_DIR, "user.name"), email: gitConfig(env.CLAUDE_PROJECT_DIR, "user.email") })
  };
  const lines = createInterface({ input: process.stdin });
  lines.on("line", (line) => {
    if (!line.trim()) return;
    let message;
    try {
      message = JSON.parse(line);
    } catch {
      process.stdout.write(`${JSON.stringify({ jsonrpc: "2.0", id: null, error: { code: -32700, message: "Parse error" } })}
`);
      return;
    }
    void handleMessage(message, deps).then((response) => {
      if (response) process.stdout.write(`${JSON.stringify(response)}
`);
    });
  });
}
if (process.argv[1] && path2.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
export {
  TOOL_DEFINITION,
  TOOL_NAME,
  callListSessionInputs,
  handleMessage
};
